"""empty message

Revision ID: 6cf6f89619f
Revises: None
Create Date: 2015-06-08 14:25:11.589242

"""

# revision identifiers, used by Alembic.
revision = '6cf6f89619f'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    ### end Alembic commands ###
